
Description: S3 Bucket for notes app API koa lambda

Resources:
  NotesAppS3BucketAPILambda:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: notes-app-api-lambda-bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls : true
        BlockPublicPolicy : true
        IgnorePublicAcls : true
        RestrictPublicBuckets : true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            MaxAge: "300"
            AllowedMethods:
              - GET
              - HEAD
              - POST
              - PUT
              - DELETE
            AllowedOrigins:
              - "*"
      Tags:
        - Key: name
          Value: s3 bucket for notes app API lambda
